<?php
/**
 * Макет страницы .
 * 
 * Этот файл является частью модуля "Справочная информация".
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 * 
 * @var \Gm\View\View $this
 * @var array $errors
 */

?>
<!DOCTYPE HTML>
<html lang="<?= $this->getLang() ?>">
<head>
<meta charset="<?= $this->getCharset() ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->head() ?>
</head>

<body class="g-help">
    <?php $this->beginBody() ?>
<?php
if ($errors) :
    foreach ($errors as $error) : 
?>
    <div class="alert alert-danger" role="alert"><?= $error ?></div>
<?php
    endforeach;
endif;
?>
    <div class="container">
        <?= $content ?>
    </div>
    <?php $this->endBody() ?>
</body>

</html>